name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC时间00:00自动运行
  workflow_dispatch:      # 允许手动触发
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: platane/snk@master
        with:
          github_user_name: Mythalis-w
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark

      - name: Deploy to repository
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git commit -m "Update snake animation" || exit 0
          git push